### ISSUE TITLE
是用layer.msg时候报这个错

### ISSUE THREAD

**Issue by zhuzhuppx** [zuoyanart/vue-layer#16]
vue-layer.js?3326:1 Uncaught (in promise) TypeError: f.instancesVue[t].mask.$destroy is not a function
    at Object.f.close (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:1:2912)
    at Function.value (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:2:14552)
    at VueComponent.btnyes (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:2:18559)
    at VueComponent.boundFn [as btnyes] (webpack-internal:///./node_modules/vue/dist/vue.esm.js:192:12)
    at VueComponent.eval (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:2:18404)
    at o (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:1:28539)
    at Generator.eval [as _invoke] (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:1:29659)
    at Generator.t.(anonymous function) [as next] (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:1:28718)
    at o (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:2:3012)
    at eval (webpack-internal:///./node_modules/vue-layer/dist/vue-layer.js:2:3114)
    at <anonymous>

**Comment by zuoyanart** [comment]
谢谢， 会尽快修复

**Comment by zuoyanart** [comment]
请问是在什么情况下出现的？ 是最新版本吗？现在并没有重现
